name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3' # Use a versão do Flutter que você está usando
    - run: flutter pub get
    - name: Run Dart Analyzer
      run: flutter analyze
    - name: Check code formatting
      run: flutter format --set-exit-if-changed .
    - run: flutter test
    - run: flutter build apk # ou flutter build ios, dependendo do seu alvo
