name: CI

on:
  push:
    branches: [ flutterflow ]
  pull_request:
    branches: [ flutterflow ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Adicione os passos necessários para configurar o ambiente do seu projeto
    # Por exemplo, instalar dependências do Flutter, configurar emuladores, etc.

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$HOME/flutter/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: flutter pub get

    # Coloque aqui outros comandos necessários para preparar o ambiente de teste

    # Aqui você executa os testes
    - name: Run tests
      run: flutter test
